### Register a new user
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "yourPassword"
}

###

### Log in with the registered user
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "yourPassword"
}

###
GET http://localhost:8080/api/user/profile
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyQGV4YW1wbGUuY29tIiwiaWF0IjoxNzU1MzY3OTc5LCJleHAiOjE3NTU0NTQzNzl9.cw-9RlVdY6algC8ORC5Kx7fZ3rau3Icz6pGmQuUeZ5T2T3yiCyrb297IHt0SsdAZAPniecmdvXd5SsQEpZuDfA

###
POST http://localhost:8080/api/cart/add
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyQGV4YW1wbGUuY29tIiwiaWF0IjoxNzU1MzY3OTc5LCJleHAiOjE3NTU0NTQzNzl9.cw-9RlVdY6algC8ORC5Kx7fZ3rau3Icz6pGmQuUeZ5T2T3yiCyrb297IHt0SsdAZAPniecmdvXd5SsQEpZuDfA
Content-Type: application/json

{
  "productId": 1,
  "quantity": 2
}
